/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TvlFlowImport } from './routes/tvl-flow'
import { Route as StatsImport } from './routes/stats'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as DisclaimerImport } from './routes/disclaimer'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as VaultsChainIdVaultAddressIndexImport } from './routes/vaults/$chainId/$vaultAddress/index'

// Create/Update Routes

const TvlFlowRoute = TvlFlowImport.update({
  id: '/tvl-flow',
  path: '/tvl-flow',
  getParentRoute: () => rootRoute,
} as any)

const StatsRoute = StatsImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const DisclaimerRoute = DisclaimerImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VaultsChainIdVaultAddressIndexRoute =
  VaultsChainIdVaultAddressIndexImport.update({
    id: '/vaults/$chainId/$vaultAddress/',
    path: '/vaults/$chainId/$vaultAddress/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsImport
      parentRoute: typeof rootRoute
    }
    '/tvl-flow': {
      id: '/tvl-flow'
      path: '/tvl-flow'
      fullPath: '/tvl-flow'
      preLoaderRoute: typeof TvlFlowImport
      parentRoute: typeof rootRoute
    }
    '/vaults/$chainId/$vaultAddress/': {
      id: '/vaults/$chainId/$vaultAddress/'
      path: '/vaults/$chainId/$vaultAddress'
      fullPath: '/vaults/$chainId/$vaultAddress'
      preLoaderRoute: typeof VaultsChainIdVaultAddressIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/stats': typeof StatsRoute
  '/tvl-flow': typeof TvlFlowRoute
  '/vaults/$chainId/$vaultAddress': typeof VaultsChainIdVaultAddressIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/stats': typeof StatsRoute
  '/tvl-flow': typeof TvlFlowRoute
  '/vaults/$chainId/$vaultAddress': typeof VaultsChainIdVaultAddressIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/stats': typeof StatsRoute
  '/tvl-flow': typeof TvlFlowRoute
  '/vaults/$chainId/$vaultAddress/': typeof VaultsChainIdVaultAddressIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/stats'
    | '/tvl-flow'
    | '/vaults/$chainId/$vaultAddress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/stats'
    | '/tvl-flow'
    | '/vaults/$chainId/$vaultAddress'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/stats'
    | '/tvl-flow'
    | '/vaults/$chainId/$vaultAddress/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  StatsRoute: typeof StatsRoute
  TvlFlowRoute: typeof TvlFlowRoute
  VaultsChainIdVaultAddressIndexRoute: typeof VaultsChainIdVaultAddressIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  StatsRoute: StatsRoute,
  TvlFlowRoute: TvlFlowRoute,
  VaultsChainIdVaultAddressIndexRoute: VaultsChainIdVaultAddressIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/disclaimer",
        "/privacy",
        "/stats",
        "/tvl-flow",
        "/vaults/$chainId/$vaultAddress/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/disclaimer": {
      "filePath": "disclaimer.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/stats": {
      "filePath": "stats.tsx"
    },
    "/tvl-flow": {
      "filePath": "tvl-flow.tsx"
    },
    "/vaults/$chainId/$vaultAddress/": {
      "filePath": "vaults/$chainId/$vaultAddress/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
