/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as VaultsChainIdVaultAddressIndexRouteImport } from './routes/vaults/$chainId/$vaultAddress/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsChainIdVaultAddressIndexRoute =
  VaultsChainIdVaultAddressIndexRouteImport.update({
    id: '/vaults/$chainId/$vaultAddress/',
    path: '/vaults/$chainId/$vaultAddress/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/vaults/$chainId/$vaultAddress/': typeof VaultsChainIdVaultAddressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/vaults/$chainId/$vaultAddress': typeof VaultsChainIdVaultAddressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/vaults/$chainId/$vaultAddress/': typeof VaultsChainIdVaultAddressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/vaults/$chainId/$vaultAddress/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/vaults/$chainId/$vaultAddress'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/disclaimer'
    | '/privacy'
    | '/vaults/$chainId/$vaultAddress/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  VaultsChainIdVaultAddressIndexRoute: typeof VaultsChainIdVaultAddressIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults/$chainId/$vaultAddress/': {
      id: '/vaults/$chainId/$vaultAddress/'
      path: '/vaults/$chainId/$vaultAddress'
      fullPath: '/vaults/$chainId/$vaultAddress/'
      preLoaderRoute: typeof VaultsChainIdVaultAddressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  VaultsChainIdVaultAddressIndexRoute: VaultsChainIdVaultAddressIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
